# Generated by Django 5.0.6 on 2024-11-05 16:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("blocks", models.JSONField(default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functions",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worksheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("main_blocks", models.JSONField(default=list)),
                ("blocks", models.JSONField(default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worksheets",
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FunctionHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="macro_sheet.function",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to="macro_sheet.function",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent"], name="macro_sheet_parent__688daa_idx"
                    ),
                    models.Index(
                        fields=["child"], name="macro_sheet_child_i_aa62d8_idx"
                    ),
                ],
                "unique_together": {("parent", "child")},
            },
        ),
        migrations.CreateModel(
            name="WorksheetFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="macro_sheet.function",
                    ),
                ),
                (
                    "worksheet",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="macro_sheet.worksheet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["worksheet"], name="macro_sheet_workshe_f17537_idx"
                    ),
                    models.Index(
                        fields=["function"], name="macro_sheet_functio_999d21_idx"
                    ),
                ],
                "unique_together": {("worksheet", "function")},
            },
        ),
    ]
