# Generated by Django 5.0.6 on 2024-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("macro_sheet", "0002_gui_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worksheet",
            name="main_blocks",
        ),
        migrations.AddField(
            model_name="worksheet",
            name="main_block",
            field=models.JSONField(default=None),
        ),
    ]
