# Generated by Django 5.0.6 on 2024-11-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("macro_sheet", "0003_remove_worksheet_main_blocks_worksheet_main_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gui",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="gui",
            name="worksheet",
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("script_code", models.TextField()),
                ("script_hash", models.CharField(max_length=64, unique=True)),
                (
                    "gui_id",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_gui",
                        to="macro_sheet.gui",
                    ),
                ),
            ],
            options={
                "db_table": "Script",
            },
        ),
    ]
