# Generated by Django 5.0.6 on 2024-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("macro_sheet", "0004_remove_gui_owner_remove_gui_worksheet_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="function",
            name="id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="worksheet",
            name="id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
