# Generated by Django 5.0.6 on 2024-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("macro_sheet", "0005_alter_function_id_alter_worksheet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="raw_blocks",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="worksheet",
            name="raw_main_block",
            field=models.JSONField(default=list),
        ),
    ]
