# Generated by Django 5.0.6 on 2024-11-25 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("macro_sheet", "0007_function_raw_blocks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="script",
            old_name="gui_id",
            new_name="gui",
        ),
    ]
