# Generated by Django 5.0.6 on 2024-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("macro_sheet", "0010_kolawlist_delete_법령목록"),
    ]

    operations = [
        migrations.CreateModel(
            name="KoOrg",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("org", models.CharField(help_text="소관부처 코드", max_length=50)),
                ("org_name", models.CharField(help_text="소관부처명", max_length=255)),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, help_text="수정일")),
            ],
            options={
                "db_table": "KoOrg",
            },
        ),
    ]
