# Generated by Django 5.0.6 on 2024-12-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("macro_sheet", "0011_koorg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kolawlist",
            name="공동부령정보",
            field=models.JSONField(blank=True, help_text="공동부령정보", null=True),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="공포번호",
            field=models.CharField(
                blank=True, help_text="공포번호", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="공포일자",
            field=models.CharField(
                blank=True, help_text="공포일자", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="법령ID",
            field=models.CharField(help_text="법령ID", max_length=100),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="법령구분명",
            field=models.CharField(
                blank=True, help_text="법령구분명", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="법령명한글",
            field=models.CharField(
                blank=True, help_text="법령명한글", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="법령상세링크",
            field=models.CharField(
                blank=True, help_text="법령상세링크", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="법령일련번호",
            field=models.CharField(help_text="법령일련번호", max_length=100),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="소관부처명",
            field=models.CharField(
                blank=True, help_text="소관부처명", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="소관부처코드",
            field=models.CharField(
                blank=True, help_text="소관부처코드", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="시행일자",
            field=models.CharField(
                blank=True, help_text="시행일자", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="자법타법여부",
            field=models.CharField(
                blank=True, help_text="자법타법여부", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="제개정구분명",
            field=models.CharField(
                blank=True, help_text="제개정구분명", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kolawlist",
            name="현행연혁코드",
            field=models.CharField(help_text="현행연혁코드", max_length=100),
        ),
    ]
