POST {{macro-host}}/worksheet/validate/
Content-Type: application/json
Authorization: Bearer {{macro-jwt}}

# 백엔드 예외처리: 현재로써는 reference block 이 있는경우 해당 id 가 존재하는지 확인함.
# 자세한 블록도메인은 domain.excalidraw 에서 확인할 수 있다.
{
      "main_block": {
        "block_type": "MAIN_BLOCK",
        "body": [
          {
            "block_type": "BASE_LOOP_BLOCK",
            "iter_cnt": "2",
            "body": [
              {
                "block_type": "BASE_LOOP_BLOCK",
                "iter_cnt": "3",
                "body": [
                  {
                    "block_type": "REFERENCE_BLOCK",
                    "reference_id": "b03c7294-1f68-459d-8c7b-1f9e1f234a29",
                    "reference_function_name": "UnKnown"
                  }
                ]
              },
              {
                "block_type": "BASE_LOOP_BLOCK",
                "iter_cnt": "3",
                "body": [
                  {
                    "block_type": "REFERENCE_BLOCK",
                    "reference_id": "c11a7da4-41ba-4947-a788-9b5398206d9b",
                    "reference_function_name": "UnKnown"
                  }
                ]
              },
              {
                "block_type": "REFERENCE_BLOCK",
                "reference_id": "de7e63ca-8315-4595-9f6e-f4652b322821",
                "reference_function_name": "UnKnown"
              }
            ]
          }
        ]
      }
}