# Python 3.11 Slim 이미지 기반
FROM python:3.11-slim

WORKDIR /workspace

# 시스템 종속성 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    git \
    net-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 전역 PATH 설정 (Poetry 설치 후 사용을 위함)
ENV PATH="/root/.local/bin:$PATH"

# 전체 프로젝트 파일 복사
COPY . ./

# 환경에 따라 자동으로 의존성 관리자 설치 및 의존성 설치
RUN if [ -f pyproject.toml ]; then \
        echo "Poetry 환경 감지됨. Poetry 설치 및 의존성 설치 시작." && \
        curl -sSL https://install.python-poetry.org | python3 - && \
        poetry config virtualenvs.create false && \
        poetry install --no-root; \
    elif [ -f Pipfile ]; then \
        echo "Pipenv 환경 감지됨. Pipenv 설치 및 의존성 설치 시작." && \
        pip install --upgrade pip && pip install pipenv && \
        pipenv install --system --deploy; \
    elif [ -f requirements.txt ]; then \
        echo "Pip 환경 감지됨. Pip을 통한 의존성 설치 시작." && \
        pip install --upgrade pip && \
        pip install -r requirements.txt; \
    else \
        echo "의존성 관리 파일을 찾을 수 없습니다."; \
    fi

EXPOSE 8000
